title: 'The Lowcarb Dude'
default_lang: es
author:
  name: 'Luis Monterrubio'
  email: luis.monterrubio@me.com
metadata:
  description: '“Anyone can cook healthy, delicious and beautifully” Yes I eat lotsa fat and feel good LCHF | Keto | Lowcarb evangelist'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
taxonomies: [category,tag,month]

summary:
  size: 100
  striptags: true

# Image must be uploaded to your theme /images/ directory.
global_featured_image: featured.jpg

social:
  - text: facebook
    url: "http://www.facebook.com/getgrav"
  - text: twitter
    url: "http://www.twitter.com/getgrav"
  - text: google-plus
    url: "http://www.plus.google.com/getgrav"
  - text: linkedin
    url: "http://www.linkedin.com/getgrav"
  - text: youtube-play
    url: "http://www.youtube.com/getgrav"
  - text: home
    url: "http://www.getgrav.org"

slider:
  - image: slide3.jpg
    title: A very delicious blog
    url: "#"
  - image: slide1.jpg
    title: Duis autem
    url: "#"
  - image: slide2.jpg
    title: Pumpkin recipe
    url: "#"

menu:
  - url: error
    text: Error Page

# Copyright
copyright: Designed and developed by <a title="WebMan WordPress Themes" href="http://www.webmandesign.eu/"><strong>WebMan Design</strong></a>, Ported By <a href="http://www.getgrav.org" rel="dofollow" target="_blank" title="Grav">Grav Team</a>
